Add meson build system support
kubo/funchook pull request #56
Opened 2024-09-15 23:21 UTC by mochaaP

2025-01-21 22:33 UTC, eli-schwartz requested changes

2025-01-21 22:33 UTC, eli-schwartz commented on .gitignore
> +compile_commands.json
I recognize this! It's totally wrong. See https://github.com/toptal/gitignore/pull/537

"toptal" is totally unmaintained and IMO also totally junk. Please delete all of it. :)

2025-01-21 22:35 UTC, mochaaP commented on .gitignore
> +compile_commands.json
ack

2025-01-21 22:54 UTC, mochaaP commented on .gitignore
> +compile_commands.json
done, thanks :)

2025-09-28 02:24 UTC, kubo commented
Thank you for contribution.
Unfortunately, due to a shift in my personal interests, this project is now archived.
Consequently, I have closed all open issues and pull requests.

If you're looking for a successor project, please check [the network graph](https://github.com/kubo/funchook/network) to see if any forks have continued development.

2025-09-28 02:24 UTC, closed without merging